### PR TITLE
Remove Server Wrapper + change test target in Makefile

### PR DESCRIPTION
**Pull request by Nexucis**
* the Server wrapper wasn't really usefull and there was too much server interface/struct at the same time. That's causing some headache while reading the code ;)

* I changed a bit the Makefile target **test** because not everybody has gcc on his laptop and for the development you don't need everytime to see the test coverage. You are more looking at the test result

### CODE REVIEW

**Comment by slrtbtfs** [comment]
> the Server wrapper wasn't really usefull and there was too much server interface/struct at the same time. That's causing some headache while reading the code ;)

It actually exists for a reason, which is to keep the godoc documentation clean. By using this wrapper, only the exported `Server` methods are visible in the documentation and don't get lost in the noise of [these methods](https://github.com/prometheus-community/promql-langserver/blob/master/langserver/notImplemented.go).

> I changed a bit the Makefile target test because not everybody has gcc on his laptop and for the development you don't need everytime to see the test coverage. You are more looking at the test result.

Is gcc required for computing the test coverage?

Also, we should keep using the race detector since it has found a couple of bugs in the past and the `langserver/cache` package contains some tricky synchronisation.

**Comment by Nexucis** [comment]
> It actually exists for a reason, which is to keep the godoc documentation clean. By using this wrapper, only the exported Server methods are visible in the documentation and don't get lost in the noise of these methods.

When you are talking about the `Server`, are you talking about the interface ? 

But otherwise, that's not the good way to handle this things. If you want to export some specific methods, then these methods should come from an interface. Then you have a method that is public which returns an instance of this interface. And then your should be fine like that :)

Adding a struct that wrappes another struct just for the documentation and it reducing the code clarity and quality is a bit pity I think.

> Is gcc required for computing the test coverage?

Actually it's more the option `-race` that required gcc : 

```bash
go test -race ./...

# runtime/cgo
exec: "gcc": executable file not found in %PATH%
```

> Also, we should keep using the race detector since it has found a couple of bugs in the past and the langserver/cache package contains some tricky synchronization.

Don't worry the CI is still running the previous command. Like that it should be safe.

**Comment by slrtbtfs** [comment]
> > It actually exists for a reason, which is to keep the godoc documentation clean. By using this wrapper, only the exported Server methods are visible in the documentation and don't get lost in the noise of these methods.
> 
> When you are talking about the `Server`, are you talking about the interface ?
> 
> But otherwise, that's not the good way to handle this things. If you want to export some specific methods, then these methods should come from an interface. Then you have a method that is public which returns an instance of this interface. And then your should be fine like that :)
> 
> Adding a struct that wrappes another struct just for the documentation and it reducing the code clarity and quality is a bit pity I think.
> 

There gopls library the language server is using provides the `protocol.Server` interface, which requires implementations of all LSP features and is frequently changing. The `server` struct implements this interface. If `server` was public, all the `protocol.Server` functions would be public as well. To avoid that, we only expose the `Server` struct wrapper which has much more restricted access.

> But otherwise, that's not the good way to handle this things. If you want to export some specific methods, then these methods should come from an interface. Then you have a method that is public which returns an instance of this interface. And then your should be fine like that :)

IMHO the point of an interface is to provide an abstraction over exchangeable implementations. That doesn't seem to be what we want here.

**Comment by Nexucis** [comment]
> IMHO the point of an interface is to provide an abstraction over exchangeable implementations. That doesn't seem to be what we want here.

Well I cannot be against that. It's true the first thing of an interface is the possibility to provide multiple different implementation that respect the same contract.

But it's also the way to expose only a subset of public method. Like the minimum required to respect the contract. Then if the implementation wants to expose other public method, it's up to him.

And actually why it would be a so bad idea to think you could have multiple implementation here ? Even if at the end you have only one implementation, having an interface that defined and exposed the minimum required to have a promQL LSP working won't be so bad IMHO

**Comment by Nexucis** [comment]
But if you are strongly against this idea, then maybe we could just rename the structure to be a bit more crystal clear.

I really personally think having a struct that is just a wrapper with no more functionality is a bit shame and reduce a lot the visibility. But that's just my opinion

**Comment by slrtbtfs** [comment]
We could also completely stop returning exposing the `Server` type and just call the `Run` function directly when the server is created.

**Comment by slrtbtfs** [comment]
In general I'm not against redesigning the server Initialisation.

I just don't think this PR improves the current situation, since it trades a small improvement in code readability against exposing a large, quite unstable API.

While not everybody may have gcc installed, it's normal for software to require the presence of some development tools and it can be easily avoided by directly invocating the `go` command. Since the language server protocol includes a complex combination of synchronized data structures and async communication, I'd rather leave the race detector enabled.

**Comment by Nexucis** [comment]
Mmm ok :). Well I'll close this PR then.
Thanks for the discussion that was interesting :)

**Pull request closed without merging**
